"""add_details_synced_at_to_pull_requests

Revision ID: 4593294b3e8c
Revises: d4e5f6g7h890
Create Date: 2026-01-26 18:13:49.099249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4593294b3e8c'
down_revision: Union[str, None] = 'd4e5f6g7h890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pull_requests', sa.Column('details_synced_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pull_requests', 'details_synced_at')
    # ### end Alembic commands ###
