"""add github models

Revision ID: acd5ad9b6546
Revises: 
Create Date: 2026-01-23 15:20:12.257485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acd5ad9b6546'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name')
    )
    op.create_index(op.f('ix_repositories_github_id'), 'repositories', ['github_id'], unique=True)
    op.create_table('pull_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.BigInteger(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('draft', sa.Boolean(), nullable=False),
    sa.Column('author_login', sa.String(length=255), nullable=False),
    sa.Column('author_avatar', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('merged_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('commits_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pull_requests_github_id'), 'pull_requests', ['github_id'], unique=True)
    op.create_table('commits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha', sa.String(length=40), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('pr_id', sa.Integer(), nullable=True),
    sa.Column('author_login', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('committed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_requests.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commits_sha'), 'commits', ['sha'], unique=True)
    op.create_table('pr_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.BigInteger(), nullable=False),
    sa.Column('pr_id', sa.Integer(), nullable=False),
    sa.Column('author_login', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pr_comments_github_id'), 'pr_comments', ['github_id'], unique=True)
    op.create_table('pr_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.BigInteger(), nullable=False),
    sa.Column('pr_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_login', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pr_reviews_github_id'), 'pr_reviews', ['github_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pr_reviews_github_id'), table_name='pr_reviews')
    op.drop_table('pr_reviews')
    op.drop_index(op.f('ix_pr_comments_github_id'), table_name='pr_comments')
    op.drop_table('pr_comments')
    op.drop_index(op.f('ix_commits_sha'), table_name='commits')
    op.drop_table('commits')
    op.drop_index(op.f('ix_pull_requests_github_id'), table_name='pull_requests')
    op.drop_table('pull_requests')
    op.drop_index(op.f('ix_repositories_github_id'), table_name='repositories')
    op.drop_table('repositories')
    # ### end Alembic commands ###
